languageCode = "en-us"
title = "Chao-Chun Hsu"
baseURL = "https://chaochunhsu.github.io/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"
update="Lastest update: 12/15/2019"

[params]
  update="Lastest update: 12/15/2019"
  description = "Chao-Chun Hsu"
  description_zh = "徐朝駿"
  email = "Chao-Chun [dot] Hsu<br>[at] colorado [dot] edu"
  codePenUser = "Heydon"
